# Generated by Django 2.2 on 2021-05-10 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expensestitle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensestitle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
