# Generated by Django 2.2 on 2021-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210512_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestitle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
