# Generated by Django 3.1 on 2020-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201010_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/images/favicon.png', null=True, upload_to='images/'),
        ),
    ]
