# Generated by Django 3.1 on 2020-10-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201011_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/image.jpg', null=True, upload_to='images/'),
        ),
    ]
