# Generated by Django 3.1 on 2020-10-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201011_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/images/image.jpg', null=True, upload_to='images/'),
        ),
    ]
