# Generated by Django 2.2 on 2021-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/media/images/profile.png', null=True, upload_to='images/'),
        ),
    ]
